name: push
on:
  push:
    branches:
      - main
    paths:
      - 'go.mod'
      - '.github/workflows/push.yml'
      - '.github/licenses.tmpl'
env:
  GOPACKAGE: github.com/andyfeller/gh-dependency-report
  BRANCH: update-licenses-${{ github.sha }}
  COMMITTER_NAME: License Updater AF
  COMMITTER_EMAIL: 390762+license-updated-af[bot]@users.noreply.github.com
jobs:
  license-update:
    name: Update OSS license notices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Setup Git
        run: |
          git config --local user.name "$COMMITTER_NAME"
          git config --local user.email "$COMMITTER_EMAIL"

          git checkout -b "$BRANCH"

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Generate Go license notices
        run: |
          go install github.com/google/go-licenses@latest
          go-licenses report $GOPACKAGE --template .github/licenses.tmpl > third-party-licenses.md
          go-licenses save $GOPACKAGE --save_path=third-party

          git add third-party third-party-licenses.md
          git commit -m "Generate licenses - $GITHUB_SHA"
          git push origin "$BRANCH"

      - name: Open pull request
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr create \
              --title "License Update - $GITHUB_SHA" \
              --body "This PR updates the license notices for all third-party dependencies" \
              --base main \
              --head "$BRANCH"
